"""Render scan findings to plain text and self-contained HTML reports."""

from __future__ import annotations

import html
import time

from .model import Finding, Severity


def _sort_key(f: Finding):
    # Most severe first, then by check then target.
    return (-int(f.severity), f.check, f.target, f.title)


def summary_line(findings: list[Finding]) -> str:
    counts = {s: 0 for s in Severity}
    for f in findings:
        counts[f.severity] += 1
    parts = [f"{counts[s]} {s.label}" for s in reversed(list(Severity)) if counts[s]]
    return " | ".join(parts) if parts else "No findings"


def to_text(findings: list[Finding], meta: dict | None = None) -> str:
    meta = meta or {}
    lines: list[str] = []
    lines.append("=" * 72)
    lines.append("CyberSuite Security Scan Report")
    lines.append("=" * 72)
    lines.append(f"Generated : {time.strftime('%Y-%m-%d %H:%M:%S')}")
    for k, v in meta.items():
        lines.append(f"{k:<10}: {v}")
    lines.append(f"Summary   : {summary_line(findings)}")
    lines.append("")

    actionable = [f for f in findings if f.severity >= Severity.MEDIUM]
    lines.append(f"ACTION ITEMS ({len(actionable)} finding(s) at MEDIUM or above)")
    lines.append("-" * 72)
    if not actionable:
        lines.append("No medium-or-higher issues found. Nice work — keep patching and re-scan.")
    for f in sorted(actionable, key=_sort_key):
        lines.append(f"[{f.severity.label.upper()}] {f.title}")
        if f.target:
            lines.append(f"    Target        : {f.target}")
        for para in f.detail.splitlines():
            lines.append(f"    {para}")
        if f.recommendation:
            lines.append(f"    -> FIX: {f.recommendation}")
        lines.append("")

    info = [f for f in findings if f.severity < Severity.MEDIUM]
    lines.append(f"INFORMATIONAL ({len(info)})")
    lines.append("-" * 72)
    for f in sorted(info, key=_sort_key):
        lines.append(f"[{f.severity.label.upper()}] {f.title}"
                     + (f"  ({f.target})" if f.target else ""))
        for para in f.detail.splitlines():
            if para.strip():
                lines.append(f"    {para}")
    lines.append("")
    lines.append("Generated by CyberSuite. Audit only systems you own or are authorised to test.")
    return "\n".join(lines)


def to_html(findings: list[Finding], meta: dict | None = None) -> str:
    meta = meta or {}
    counts = {s: 0 for s in Severity}
    for f in findings:
        counts[f.severity] += 1

    def esc(s: str) -> str:
        return html.escape(s).replace("\n", "<br>")

    chips = "".join(
        f'<span class="chip" style="background:{s.color}">{counts[s]} {s.label}</span>'
        for s in reversed(list(Severity)) if counts[s]
    ) or '<span class="chip" style="background:#3aa657">No findings</span>'

    rows = []
    for f in sorted(findings, key=_sort_key):
        rec = f'<div class="fix"><b>Fix:</b> {esc(f.recommendation)}</div>' if f.recommendation else ""
        rows.append(f"""
        <div class="card" style="border-left:6px solid {f.severity.color}">
          <div class="cardhead">
            <span class="sev" style="background:{f.severity.color}">{f.severity.label}</span>
            <span class="ttl">{esc(f.title)}</span>
            {f'<span class="tgt">{esc(f.target)}</span>' if f.target else ''}
          </div>
          <div class="detail">{esc(f.detail)}</div>
          {rec}
        </div>""")

    meta_rows = "".join(
        f"<tr><td>{esc(str(k))}</td><td>{esc(str(v))}</td></tr>" for k, v in meta.items()
    )

    return f"""<!doctype html>
<html><head><meta charset="utf-8"><title>CyberSuite Report</title>
<style>
 body {{ font-family: -apple-system, Segoe UI, Roboto, sans-serif; margin:0; background:#f4f6f9; color:#1f2430; }}
 header {{ background:#12203a; color:#fff; padding:22px 28px; }}
 header h1 {{ margin:0 0 6px; font-size:20px; }}
 .chip {{ display:inline-block; color:#fff; border-radius:12px; padding:3px 10px; font-size:12px; margin:3px 5px 0 0; }}
 .wrap {{ max-width:960px; margin:20px auto; padding:0 16px; }}
 table.meta {{ font-size:13px; border-collapse:collapse; margin-bottom:14px; }}
 table.meta td {{ padding:2px 12px 2px 0; color:#4a5568; }}
 .card {{ background:#fff; border-radius:8px; padding:14px 16px; margin:10px 0; box-shadow:0 1px 3px rgba(0,0,0,.08); }}
 .cardhead {{ display:flex; align-items:center; gap:10px; flex-wrap:wrap; }}
 .sev {{ color:#fff; font-size:11px; font-weight:700; padding:2px 8px; border-radius:10px; text-transform:uppercase; }}
 .ttl {{ font-weight:600; }}
 .tgt {{ margin-left:auto; font-family:monospace; font-size:12px; color:#5a6577; }}
 .detail {{ font-size:13px; color:#38414f; margin-top:8px; white-space:normal; }}
 .fix {{ font-size:13px; margin-top:8px; background:#f0f5ff; border-radius:6px; padding:8px 10px; }}
 footer {{ text-align:center; color:#8a94a6; font-size:12px; padding:20px; }}
</style></head>
<body>
 <header>
   <h1>&#128737; CyberSuite Security Scan Report</h1>
   <div>Generated {time.strftime('%Y-%m-%d %H:%M:%S')}</div>
   <div style="margin-top:8px">{chips}</div>
 </header>
 <div class="wrap">
   <table class="meta">{meta_rows}</table>
   {''.join(rows) if rows else '<p>No findings.</p>'}
 </div>
 <footer>Generated by CyberSuite &middot; Audit only systems you own or are authorised to test.</footer>
</body></html>"""
